name: Docker CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker image and Push the image to DockerHUB
      run: docker build -t front .

    - name: Deploy Docker container
      run: |
        docker stop front || true
        docker rm front || true
        docker run --restart unless-stopped --name front -dp 3000:3000 front
        docker image prune -f
